import type { Metadata } from 'next';
import { SITE_NAME } from '@/config';

interface PageMetaInput {
  title: string;
  description: string;
  /** Route path with trailing slash, e.g. "/courses/". */
  path: string;
  noindex?: boolean;
}

// The branded 1200×630 card generated by src/app/opengraph-image.tsx. A page
// that sets its own Open Graph fields must name it explicitly, otherwise the
// image is dropped.
export const DEFAULT_SHARE_IMAGE = {
  url: '/opengraph-image',
  width: 1200,
  height: 630,
  type: 'image/jpeg',
  alt: 'EduSolve — one-on-one online tuition for Gulf families',
};

// Consistent per-page metadata: title, description, canonical URL and the
// matching Open Graph / Twitter fields, including the share image.
export function pageMetadata({ title, description, path, noindex }: PageMetaInput): Metadata {
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: { type: 'website', siteName: SITE_NAME, locale: 'en_IN', title, description, url: path, images: [DEFAULT_SHARE_IMAGE] },
    twitter: { card: 'summary_large_image', title, description, images: [DEFAULT_SHARE_IMAGE.url] },
    ...(noindex ? { robots: { index: false, follow: true } } : {}),
  };
}
