import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import PageHero from '../components/ui/PageHero';
import CountryPicker from '../components/forms/CountryPicker';
import { CheckIcon, WhatsAppIcon, PhoneIcon, MailIcon, PinIcon } from '../components/icons';
import { CONTACT } from '../data/site';
import { CONTACT_FORM_OPTIONS } from '../data/content';
import { countryCode, nameError, requiredError, submitToWeb3Forms } from '../lib/forms';

const EMPTY_FORM = { name: '', phone: '', country: '', grade: '', curriculum: '', subject: '', time: '', notes: '' };
const inputClass = 'w-full box-border border-[1.5px] border-[#e2e5df] rounded-xl px-[15px] py-[13px] font-sans text-[15.5px] text-brand-ink bg-white outline-none transition-colors focus:border-brand-green';
const labelClass = 'block font-heading font-semibold text-[13.5px] text-[#2c3338] mb-[7px]';
const CONTACT_CARDS = [
  { key: 'wa', href: CONTACT.whatsappUrl, external: true, Icon: WhatsAppIcon, iconBg: 'bg-whatsapp', title: 'WhatsApp', value: CONTACT.phone },
  { key: 'call', href: CONTACT.phoneHref, external: false, Icon: PhoneIcon, iconBg: 'bg-brand-red', title: 'Call us', value: CONTACT.phone },
  { key: 'mail', href: CONTACT.emailHref, external: false, Icon: MailIcon, iconBg: 'bg-brand-ink', title: 'Email', value: CONTACT.email },
  { key: 'loc', href: null, external: false, Icon: PinIcon, iconBg: 'bg-brand-green', iconColor: 'text-brand-ink', title: 'Based in', value: CONTACT.location },
];
const FieldError = ({ children }) => children ? <p className="mt-1.5 text-[12.5px] font-semibold text-brand-red" role="alert">{children}</p> : null;

export default function Contact() {
  const [form, setForm] = useState(EMPTY_FORM); const [touched, setTouched] = useState({});
  const [submitted, setSubmitted] = useState(false); const [submitError, setSubmitError] = useState(''); const [sending, setSending] = useState(false);
  const errors = useMemo(() => ({ name: nameError(form.name, 'Parent / student name'), phone: requiredError(form.phone, 'WhatsApp number'), country: requiredError(form.country, 'Country'), grade: requiredError(form.grade, 'Class / grade'), curriculum: requiredError(form.curriculum, 'Curriculum'), subject: !form.subject.trim() ? 'Subjects needed is required.' : form.subject.trim().length < 3 ? 'Subjects needed must be at least 3 characters.' : '', time: requiredError(form.time, 'Preferred time') }), [form]);
  const update = (key, numeric = false) => (event) => { const value = numeric ? event.target.value.replace(/\D/g, '') : event.target.value; setForm((previous) => ({ ...previous, [key]: value })); setTouched((previous) => ({ ...previous, [key]: true })); setSubmitError(''); };
  const blur = (key) => () => setTouched((previous) => ({ ...previous, [key]: true }));
  const setCountry = (country) => { setForm((previous) => ({ ...previous, country })); setTouched((previous) => ({ ...previous, country: true })); setSubmitError(''); };
  const handleSubmit = async (event) => { event.preventDefault(); setTouched({ name: true, phone: true, country: true, grade: true, curriculum: true, subject: true, time: true }); if (Object.values(errors).some(Boolean)) return; setSending(true); setSubmitError(''); try { await submitToWeb3Forms({ form_type: 'Free demo class booking', parent_student_name: form.name.trim(), whatsapp_number: `${countryCode(form.country)} ${form.phone}`, country: form.country, grade_class: form.grade, curriculum: form.curriculum, subjects_needed: form.subject.trim(), preferred_time: form.time, notes: form.notes.trim() || 'Not provided' }, 'New Free Demo Booking — EduSolve'); setSubmitted(true); } catch (error) { setSubmitError(error.message || 'Something went wrong. Please try again.'); } finally { setSending(false); } };
  const errorClass = (key) => touched[key] && errors[key] ? 'border-brand-red' : '';
  return <><PageHero badge="Book a free demo" title="Let's find the right tutor for your child">Fill in a few details and we’ll arrange a free one-on-one demo class. Prefer to chat? Reach us on WhatsApp anytime.</PageHero><section className="px-6 pt-5 pb-20 bg-white"><div className="max-w-[1120px] mx-auto grid gap-9 min-[900px]:gap-12 grid-cols-1 min-[900px]:grid-cols-[1.05fr_0.95fr] items-start"><div className="bg-white border border-[#eceee9] rounded-3xl px-8 py-[34px] shadow-[0_10px_34px_rgba(22,26,29,.07)]">{submitted ? <div className="text-center px-2.5 py-[30px]"><div className="w-[72px] h-[72px] rounded-full bg-surface-leaf flex items-center justify-center mx-auto mb-5 text-brand-green-dark"><CheckIcon size={38} /></div><h2 className="font-heading font-extrabold text-[26px] mb-3">Thank you! 🎉</h2><p className="text-base leading-relaxed text-body mb-6 max-w-[380px] mx-auto">We’ve received your request and will reach out on WhatsApp shortly to schedule your child’s free demo class.</p><a href={CONTACT.whatsappUrl} target="_blank" rel="noopener noreferrer" className="btn bg-brand-green text-brand-ink text-[15px] px-6 py-3.5">Message us now on WhatsApp</a></div> : <form onSubmit={handleSubmit} noValidate><h2 className="font-heading font-extrabold text-[23px] mb-[22px]">Book your free demo class</h2><div className="flex flex-col gap-4">
    <div><label className={labelClass} htmlFor="name">Parent / Student Name *</label><input id="name" className={`${inputClass} ${errorClass('name')}`} value={form.name} onChange={update('name')} onBlur={blur('name')} placeholder="Your full name" /><FieldError>{touched.name && errors.name}</FieldError></div>
    <div className="grid gap-4 grid-cols-1 min-[520px]:grid-cols-2"><div><label className={labelClass} htmlFor="phone">WhatsApp Number *</label><div className={`flex overflow-hidden rounded-xl border-[1.5px] bg-white focus-within:border-brand-green ${errorClass('phone') || 'border-[#e2e5df]'}`}><span className="flex items-center border-r border-[#e2e5df] px-3 text-sm text-body whitespace-nowrap">{countryCode(form.country) || 'Code'}</span><input id="phone" className="min-w-0 flex-1 px-3 py-[13px] font-sans text-[15.5px] text-brand-ink outline-none" type="tel" inputMode="numeric" value={form.phone} onChange={update('phone', true)} onBlur={blur('phone')} placeholder="WhatsApp number" /></div><FieldError>{touched.phone && errors.phone}</FieldError></div><div><label className={labelClass} htmlFor="country">Country *</label><CountryPicker id="country" value={form.country} onChange={setCountry} error={touched.country && errors.country} /><FieldError>{touched.country && errors.country}</FieldError></div></div>
    <div className="grid gap-4 grid-cols-1 min-[520px]:grid-cols-2"><div><label className={labelClass} htmlFor="grade">Class / Grade *</label><select id="grade" className={`${inputClass} ${errorClass('grade')}`} value={form.grade} onChange={update('grade')} onBlur={blur('grade')}><option value="">Select grade</option>{CONTACT_FORM_OPTIONS.grades.filter((g) => g !== 'Select grade').map((g) => <option key={g}>{g}</option>)}</select><FieldError>{touched.grade && errors.grade}</FieldError></div><div><label className={labelClass} htmlFor="curriculum">Curriculum *</label><select id="curriculum" className={`${inputClass} ${errorClass('curriculum')}`} value={form.curriculum} onChange={update('curriculum')} onBlur={blur('curriculum')}><option value="">Select curriculum</option>{CONTACT_FORM_OPTIONS.curricula.filter((c) => c !== 'Select curriculum').map((c) => <option key={c}>{c}</option>)}</select><FieldError>{touched.curriculum && errors.curriculum}</FieldError></div></div>
    <div className="grid gap-4 grid-cols-1 min-[520px]:grid-cols-2"><div><label className={labelClass} htmlFor="subject">Subjects Needed *</label><input id="subject" className={`${inputClass} ${errorClass('subject')}`} value={form.subject} onChange={update('subject')} onBlur={blur('subject')} placeholder="e.g. Maths, Physics" /><FieldError>{touched.subject && errors.subject}</FieldError></div><div><label className={labelClass} htmlFor="time">Preferred Time *</label><select id="time" className={`${inputClass} ${errorClass('time')}`} value={form.time} onChange={update('time')} onBlur={blur('time')}><option value="">Select preferred time</option>{CONTACT_FORM_OPTIONS.times.filter((t) => !/select/i.test(t)).map((t) => <option key={t}>{t}</option>)}</select><FieldError>{touched.time && errors.time}</FieldError></div></div>
    <div><label className={labelClass} htmlFor="notes">Anything else we should know?</label><textarea id="notes" className={`${inputClass} resize-y`} rows="3" value={form.notes} onChange={update('notes')} placeholder="Tell us about your child's goals or any specific needs" /></div><button type="submit" disabled={sending} className="w-full bg-brand-red text-white border-none cursor-pointer disabled:cursor-wait disabled:opacity-70 font-heading font-bold text-[16.5px] py-4 rounded-xl shadow-[0_10px_24px_rgba(210,3,33,.28)] transition-transform hover:-translate-y-0.5">{sending ? 'Sending request…' : 'Request My Free Demo'}</button><FieldError>{submitError}</FieldError><p className="text-[12.5px] text-muted text-center leading-normal">By submitting, you agree to be contacted about your demo. We respect your privacy — see our <Link to="/privacy" className="font-semibold no-underline text-brand-red">Privacy Policy</Link>.</p></div></form>}</div>
    <div><h2 className="font-heading font-extrabold text-[23px] mb-[18px]">Or reach us directly</h2><div className="grid gap-4 grid-cols-1 min-[520px]:grid-cols-2 mb-[26px]">{CONTACT_CARDS.map((card) => { const inner = <><div className={`w-11 h-11 rounded-xl ${card.iconBg} ${card.iconColor ?? 'text-white'} flex items-center justify-center mb-3`}><card.Icon size={22} /></div><div className="font-heading font-bold text-[15px] text-brand-ink">{card.title}</div><div className="text-[13.5px] text-body mt-0.5">{card.value}</div></>; const cardClass = 'bg-surface-mint border border-[#e6e9df] rounded-2xl px-5 py-[22px] block transition-colors hover:border-brand-green no-underline'; return card.href ? <a key={card.key} href={card.href} {...(card.external ? { target: '_blank', rel: 'noopener noreferrer' } : {})} className={cardClass}>{inner}</a> : <div key={card.key} className={cardClass}>{inner}</div>; })}</div><div className="bg-brand-ink rounded-[18px] px-6 py-[26px] text-white"><h3 className="font-heading font-bold text-[17px] mb-3">Class timings</h3><p className="text-[14.5px] leading-relaxed text-[#c6cbce] mb-3.5">We schedule around Gulf time zones with flexible evening and weekend slots to suit your family.</p><div className="flex items-center gap-2.5 text-sm text-brand-green font-semibold"><span className="w-2 h-2 rounded-full bg-brand-green inline-block" />Typically replies within a few hours</div></div></div>
  </div></section></>;
}
